import = ['C:\Users\sigur\AppData\Roaming\alacritty\monokai_charcoal.toml']

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
magenta = "#f332fa"

[colors.normal]
magenta = "#f332fa"

[colors.primary]
background = "#272822"

[colors.selection]
background = "#868686"
text = "CellForeground"

[cursor.style]
shape = "Beam"

[font]
size = 11.5

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
startup_mode = "Maximized"
decorations = "none"
