# direction_keys = "HjklAndArrows"

# [brush_keys]
# fg = { Char = "f" }
# bg = { Char = "b" }
# character = { Char = "g" }
# modifiers = { Char = "m" }
# all = { Char = "a" }

# # [color_theme]
# # canvas_base = { add_modifier = "", sub_modifier = "" }
# # status_bar = { add_modifier = "", sub_modifier = "" }

# color_theme_preset = "Ubuntu"
# color_theme_preset = "Monokai"

# autoreload_config = false
# [keymaps.actions]
# " r" = { ReloadConfig = {} }

message_popup_suppress_keystroke = false

[numbers.row]
enable = true
relative = false

[numbers.column]
relative = false

[color_theme.status_bar]
# fg = "Yellow"

[color_theme.canvas_base]
# bg = "#000000"
# fg = "#ffff00"

[input_mode.n.keymaps.actions]
"<C-k>" = { ChangeMode = { mode = "n" }}
" q" = { Quit = {} }
" 1" = { ForceQuit = {} }
" w" = { Save = {} }
" x" = { SaveQuit = {} }
"øq" = { Quit = {} }
"ø1" = { ForceQuit = {} }
"øw" = { Save = {} }
"øx" = { SaveQuit = {} }
"ør" = { ReloadConfig = {} }

[input_mode.n.keymaps.actions_repeatable]
"U" = { "Redo" = {} }


[input_mode.n.keymaps.motions]
# Shortcut intended for drawing lines more quickly
"L" = { GoToMark = { jump = "Diagonals", slot = "l" } }

[input_mode.n.keymaps.continuous_region_relative_types]

